In [1]:
import swiftest
import os
import xarray as xr
import numpy as np
os.getcwd()

'/home/daminton/git/swiftest/examples/symba_mars_disk'

In [2]:
sim = swiftest.Simulation(param_file="param.in")
sim.bin2xr()


Reading Swiftest file param.in

Creating Dataset
Successfully converted 6 output frames.
Swiftest simulation data stored as xarray DataSet .ds


In [3]:
sim.ds['status']

<xarray.DataArray 'status' (id: 1521)>
array(['ACTIVE', 'ACTIVE', 'ACTIVE', ..., 'ACTIVE', 'ACTIVE', 'ACTIVE'],
      dtype='<U17')
Coordinates:
  * id       (id) int32 0 1 2 3 4 5 6 7 ... 1514 1515 1516 1517 1518 1519 1520

In [4]:
ds = xr.open_dataset('bin.nc')

In [5]:
sim.ds['status'].sel(id=726)

<xarray.DataArray 'status' ()>
array('Supercatastrophic', dtype='<U17')
Coordinates:
    id       int32 726

In [6]:
sim.ds['discard_time']

<xarray.DataArray 'discard_time' (id: 1521)>
array([ 0.000000e+000,  6.013470e-154,  6.013470e-154, ..., -1.797693e+308,
       -1.797693e+308, -1.797693e+308])
Coordinates:
  * id       (id) int32 0 1 2 3 4 5 6 7 ... 1514 1515 1516 1517 1518 1519 1520

In [7]:
dslost = sim.ds.where(sim.ds['status'] != "ACTIVE", drop=True)

In [8]:
dslost['discard_time']

<xarray.DataArray 'discard_time' (id: 2)>
array([2400., 2400.])
Coordinates:
  * id       (id) int32 230 726

In [9]:
lastloss = dslost.where(dslost['discard_time'] == 98400.0, drop=True)

In [10]:
dsactive = sim.ds.where(sim.ds['status'] == "ACTIVE", drop=True)

In [11]:
dsactive

<xarray.Dataset>
Dimensions:          (id: 1519, time: 6)
Coordinates:
  * time             (time) float64 0.0 600.0 1.2e+03 1.8e+03 2.4e+03 3e+03
  * id               (id) int32 0 1 2 3 4 5 6 ... 1515 1516 1517 1518 1519 1520
Data variables: (12/57)
    npl              (time, id) float64 1.5e+03 1.5e+03 ... 1.518e+03 1.518e+03
    ntp              (time, id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    name             (id) object 'Mars' 'Body2' ... 'Newbody0001520'
    particle_type    (id) object 'Central Body' ... 'Massive Body'
    xhx              (time, id) float64 0.0 -2.358e+06 ... -3.489e+06 -3.476e+06
    xhy              (time, id) float64 0.0 8.604e+06 ... -8.532e+06 -8.571e+06
    ...               ...
    discard_xhy      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_xhz      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_vhx      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_vhy      (id) float64 0.0 2.122e-314 2.122e-314 ... 0.0 0.0 0.0
    discard_vhz      (id) float64 0.0 3.024e-153 3.024e-153 ... 0.0 0.0 0.0
    discard_body_id  (id) float64 -2.147e+09 -2.147e+09 ... -2.147e+09

In [13]:
lastadd = sim.ds.where(sim.ds['origin_time'] == 2400.0, drop=True)

In [14]:
lastadd

<xarray.Dataset>
Dimensions:          (id: 20, time: 6)
Coordinates:
  * time             (time) float64 0.0 600.0 1.2e+03 1.8e+03 2.4e+03 3e+03
  * id               (id) int32 1501 1502 1503 1504 1505 ... 1517 1518 1519 1520
Data variables: (12/57)
    npl              (time, id) float64 1.5e+03 1.5e+03 ... 1.518e+03 1.518e+03
    ntp              (time, id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0
    name             (id) object 'Newbody0001501' ... 'Newbody0001520'
    particle_type    (id) object 'Massive Body' ... 'Massive Body'
    xhx              (time, id) float64 0.0 0.0 0.0 ... -3.489e+06 -3.476e+06
    xhy              (time, id) float64 0.0 0.0 0.0 ... -8.532e+06 -8.571e+06
    ...               ...
    discard_xhy      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_xhz      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_vhx      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_vhy      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_vhz      (id) float64 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
    discard_body_id  (id) float64 -2.147e+09 -2.147e+09 ... -2.147e+09

In [15]:
lastframe = dsactive.isel(time=-1, drop=True)
firstframe = sim.ds.isel(time=0, drop=True)
firstframe = firstframe.where(firstframe['a'] < 1e20, drop=True)
midframe = sim.ds.isel(time=-2, drop=True)
midframe = midframe.where(midframe['a'] < 1e20, drop=True)

In [16]:
lastframe.id

<xarray.DataArray 'id' (id: 1519)>
array([   0,    1,    2, ..., 1518, 1519, 1520], dtype=int32)
Coordinates:
  * id       (id) int32 0 1 2 3 4 5 6 7 ... 1514 1515 1516 1517 1518 1519 1520

In [17]:
lastloss.id

<xarray.DataArray 'id' (id: 0)>
array([], dtype=int32)
Coordinates:
  * id       (id) int32

In [18]:
lastframe['Gmass'].sum()

<xarray.DataArray 'Gmass' ()>
array(4.28396188e+13)

In [19]:
firstframe['Gmass'].sum()

<xarray.DataArray 'Gmass' ()>
array(4.28396188e+13)

In [20]:
midframe['Gmass'].sum()

<xarray.DataArray 'Gmass' ()>
array(4.28396188e+13)

In [22]:
lastframe.sel(id=2)

<xarray.Dataset>
Dimensions:          ()
Coordinates:
    id               int32 2
Data variables: (12/57)
    npl              float64 1.518e+03
    ntp              float64 0.0
    name             object 'Body3'
    particle_type    object 'Massive Body'
    xhx              float64 -3.025e+06
    xhy              float64 -1.02e+07
    ...               ...
    discard_xhy      float64 0.0
    discard_xhz      float64 0.0
    discard_vhx      float64 0.0
    discard_vhy      float64 2.122e-314
    discard_vhz      float64 3.024e-153
    discard_body_id  float64 -2.147e+09