In [1]:
import numpy as np
import swiftest
import matplotlib.pyplot as plt

In [2]:
swiftersim = swiftest.Simulation(param_file="param.swifter.in", codename="Swifter")
swiftersim.bin2xr()

Reading Swifter file param.swifter.in
Reading in time 1.506e-01
Creating Dataset
Successfully converted 221 output frames.
Swifter simulation data stored as xarray DataSet .ds


In [3]:
swiftestsim = swiftest.Simulation(param_file="param.swiftest.in")
swiftestsim.bin2xr()

Reading Swiftest file param.swiftest.in
Reading in time 1.506e-01
Creating Dataset
Successfully converted 221 output frames.
Swiftest simulation data stored as xarray DataSet .ds


In [4]:
swiftdiff = swiftestsim.ds - swiftersim.ds

In [5]:
swiftdiff = swiftdiff.rename({'time' : 'time (y)'})


In [6]:
swiftdiff['vx'].plot.line(x="time (y)")

In [14]:
swiftdiff['vx'].sel(id=2)

<xarray.DataArray 'vx' (time (y): 221)>
array([ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
...
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  3.98117095e-11, -9.46069889e-11, -2.30539143e-10,
       -3.67965214e-10, -5.06869213e-10, -6.47232490e-10, -7.89038168e-10,
       -9.32266708e-10, -1.07690123e-09, -1.22292310e-09, -1.37031364e-09,
       -1.51905422e-09, -1.66912617e-09, -1.82051085e-09, -1.97318961e-09,
       -2.12714202e-09, -2.28234942e-09, -2.43879317e-09, -2.59645283e-09,
       -2.75530976e-09, -2.91534441e-09, -3.07653725e-09, -3.23886606e-09,
       -3.40231310e-09])
Coordinates:
    id        float64 2.0
  * time (y)  (time (y)) float64 0.0 0.0006845 0.001369 ... 0.1492 0.1499 0.1506

In [11]:
swiftdiff.sel(id=100)['vx']

<xarray.DataArray 'vx' (time (y): 221)>
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])
Coordinates:
    id        float64 100.0
  * time (y)  (time (y)) float64 0.0 0.0006845 0.001369 ... 0.1492 0.1499 0.1506

In [9]:
swiftersim.ds.sel(id=100)['vx']

<xarray.DataArray 'vx' (time: 221)>
array([ 0.        , -0.02730963, -0.05461883, -0.08192718, -0.10923426,
       -0.13653965, -0.16384292, -0.19114364, -0.21844141, -0.24573578,
       -0.27302634, -0.30031266, -0.32759433, -0.35487091, -0.38214199,
       -0.40940715, -0.43666596, -0.463918  , -0.49116285, -0.51840009,
       -0.5456293 , -0.57285005, -0.60006193, -0.62726452, -0.6544574 ,
       -0.68164014, -0.70881234, -0.73597358, -0.76312342, -0.79026147,
       -0.8173873 , -0.8445005 , -0.87160064, -0.89868733, -0.92576014,
       -0.95281866, -0.97986247, -1.00689117, -1.03390434, -1.06090158,
       -1.08788246, -1.11484659, -1.14179356, -1.16872296, -1.19563437,
       -1.22252741, -1.24940165, -1.27625671, -1.30309216, -1.32990762,
       -1.35670269, -1.38347696, -1.41023003, -1.43696151, -1.463671  ,
       -1.4903581 , -1.51702243, -1.54366359, -1.57028119, -1.59687484,
       -1.62344416, -1.64998874, -1.67650822, -1.70300221, -1.72947032,
       -1.75591217, -1.78232739, -1.8087156 , -1.83507643, -1.8614095 ,
       -1.88771444, -1.91399088, -1.94023846, -1.96645681, -1.99264557,
       -2.01880437, -2.04493287, -2.0710307 , -2.09709752, -2.12313297,
       -2.1491367 , -2.17510838, -2.20104766, -2.2269542 , -2.25282767,
       -2.27866774, -2.30447407, -2.33024634, -2.35598424, -2.38168744,
       -2.40735563, -2.43298851, -2.45858576, -2.48414708, -2.50967219,
       -2.53516079, -2.56061259, -2.58602731, -2.61140468, -2.63674443,
...
       -3.28166908, -3.30592115, -3.33013189, -3.3543014 , -3.37842979,
       -3.40251722, -3.42656386, -3.45056991, -3.47453562, -3.49846126,
       -3.52234715, -3.54619364, -3.57000113, -3.59377005, -3.61750092,
       -3.64119426, -3.66485068, -3.68847086, -3.71205553, -3.73560548,
       -3.75912161, -3.78260489, -3.80605637, -3.82947723, -3.85286873,
       -3.87623226, -3.89956936, -3.92288168, -3.94617105, -3.96943947,
       -3.99268912, -4.01592242, -4.03914199, -4.06235073, -4.08555183,
       -4.10874879, -4.13194551, -4.15514625, -4.17835577, -4.20157933,
       -4.2248228 , -4.24809272, -4.2713964 , -4.29474206, -4.31813893,
       -4.34159746, -4.36512951, -4.38874856, -4.41247007, -4.43631182,
       -4.46029439, -4.48444172, -4.50878191, -4.53334814, -4.55817998,
       -4.58332498, -4.60884098, -4.63479915, -4.66128825, -4.68842081,
       -4.71634199, -4.7452432 , -4.77538326, -4.80712299, -4.84098468,
       -4.87776098, -4.91873117, -4.96614064, -5.02443531, -5.10428159,
       -5.24263186, -5.9750488 ,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
               nan])
Coordinates:
    id       int64 100
  * time     (time) float64 0.0 0.0006845 0.001369 ... 0.1492 0.1499 0.1506